export * from './Movie/Movie'
export * from './Movies/Movies'
export * from './Footer/Footer'
export * from './Details/Details'
export * from './Genres/Genres'
export * from './Header/Header'
export * from './Pagination/Pagination'